import Layout from '@/components/ProLayout'
import { Inter } from 'next/font/google'
import React from 'react'
import StyledComponentsRegistry from '../lib/AntdRegistry'
import { ReduxProvider } from '@/redux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

const RootLayout = ({ children }: { children: React.ReactNode }) => (
	<html lang='en'>
		<body className={inter.className}>
			<StyledComponentsRegistry>
				<ReduxProvider>
					<Layout>{children}</Layout>
				</ReduxProvider>
			</StyledComponentsRegistry>
		</body>
	</html>
)

export default RootLayout
